work_dir: ./120xsub_result/joint/l6
run_mode: test
save_score: True
weights: ./pt_120xsub/joint_final/l6/8547.pt

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: gendata/ntu120/NTU120_XSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  data_mode: joint

test_feeder_args:
  data_path: gendata/ntu120/NTU120_XSub.npz
  split: test
  debug: False
  window_size: 120
  p_interval: [0.95]
  data_mode: joint

# model
model: model.st_gf.Model
model_args:
  len_parts: 6
  num_frames: 120
  num_joints: 25
  num_classes: 120
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 3
  use_pes: True
  koopman: none
  #dataset: ntu
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64], [256, 256, 64]]

#optim (whatever~)
weight_decay: 0.0005
base_lr: 0.1
lr_decay_rate: 0.1
save_epoch: 80
step: [60, 80]
warm_up_epoch: 5

# training
num_worker: 10
device: [0, 1]
cuda_visible_device: '0,1'
batch_size: 16
test_batch_size: 128
num_epoch: 1
nesterov: True
